---
title: '2020 NFL Team Ratings & Playoff Odds'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
library(rvest)
library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
library(htmltools)
library(htmlwidgets)
library(reactable)
library(crosstalk)
library(plotly)
library(nflfastR)
```

```{r data}
url <- "https://www.pro-football-reference.com/years/2020/"

### Get AFC conference table from pro-football-reference site
AFC_table <- url %>%
  xml2::read_html() %>%
  html_nodes(xpath = '//*[@id="AFC"]') %>%
  html_table()

AFC_table <- AFC_table[[1]]

### Get NFC conference table from pro-football-reference site
NFC_table <- url %>%
  xml2::read_html() %>%
  html_nodes(xpath = '//*[@id="NFC"]') %>%
  html_table()

NFC_table <- NFC_table[[1]]

### Combine AFC and NFC tables together
NFL_table <- rbind(AFC_table, NFC_table)

url <- "https://projects.fivethirtyeight.com/2020-nfl-predictions/?ex_cid=rrpromo"

### Get FiveThirtyEight playoff odds
FIVETHIRTYEIGHT_table <- url %>%
  xml2::read_html() %>%
  html_nodes(xpath = '//*[@id="standings-table"]') %>%
  html_table(fill = TRUE)

FIVETHIRTYEIGHT_table <- FIVETHIRTYEIGHT_table[[1]]

FIVETHIRTYEIGHT_playoffs <- FIVETHIRTYEIGHT_table %>%
  janitor::clean_names() %>%
  select("Team" = x_5,
         "Make Playoffs" = playoff_chances) %>%
  mutate(Playoffs = case_when(
    `Make Playoffs` == ">99%" ~ "99.9",
    `Make Playoffs` == "<1%" ~ "0.1",
    TRUE ~ gsub('\\%', '', `Make Playoffs`)
  )) %>%
  slice(-2) %>%
  mutate(Team = gsub('([[:upper:]]|[[:digit:]]+[[:lower:]])', ' \\1', Team)) %>%
  mutate(Team = word(Team,-2)) %>%
  mutate(Team = case_when(Team == "Washington" ~ "Football Team",
                          TRUE ~ Team))

teams_colors <- teams_colors_logos %>% 
  filter(!team_abbr %in% c("LA", "OAK", "STL", "SD"))

### Combine into cleaned table
NFL_table_clean <- NFL_table %>%
  ### Create NFL divisions column
  mutate(Division = ifelse(str_detect(Tm, "FC"), Tm, NA)) %>%
  fill(Division, .direction = "down") %>%
  ### Create NFL conferences column
  mutate(Conference = ifelse(str_detect(Division, "NFC"), "NFC", "AFC")) %>%
  ### Remove team division names from Tm column
  filter(str_detect(Tm, "FC", negate = TRUE)) %>%
  rename(Record = `W-L%`) %>%
  ### Convert W, L, T into one column named "Record"
  unite(Record, `W`, `L`, `T`, sep = "-") %>%
  ### Update team names
  mutate(Team = word(Tm, -1)) %>% 
  mutate(
    Team = case_when(
      Team == "Team" ~ "Football Team",
      TRUE ~ Team
    )
  ) %>%
  ### Join FiveThirtyEight playoff odds
  inner_join(FIVETHIRTYEIGHT_playoffs, by = c("Team" = "Team")) %>% 
  ### Join team colors from nflfastR
  inner_join(teams_colors, by = c("Team" = "team_nick")) %>% 
  ### Convert columns containing numbers from character to numeric
  mutate_at(c("SRS", "OSRS", "DSRS", "PF", "PA", "MoV", "SoS", "Playoffs"),
            as.numeric) %>%
  ### Rank SoS column from 1 to 4 with 1 containing the lowest values and 4 containing the highest
  mutate(SoS_rating = ntile(SoS, 4)) %>% 
  select(
    Conference,
    Division,
    Team,
    team_color,
    Record,
    SoS_rating,
    PF,
    PA,
    OSRS,
    DSRS,
    SRS,
    Playoffs,
    Playoff_labels = `Make Playoffs`
  )

NFL_table_clean_shared <- SharedData$new(NFL_table_clean)
```


```{r plot}
interactive_plot <-
  plot_ly(
    NFL_table_clean_shared,
    x = ~ OSRS,
    y = ~ DSRS,
    text = ~paste(Team, "<br /> Playoff Odds:", Playoff_labels),
    hoverinfo = "text",
    hovertemplate = paste(
      "<b>%{text}</b><br>",
      "<b>%{xaxis.title.text}: %{x:+.1f}</b><br>",
      "<b>%{yaxis.title.text}: %{y:+.1f}</b><br>",
      "<extra></extra>"
    ),
    marker = list(
      size = ~ Playoffs,
      sizeref = 0.1,
      sizemode = 'area',
      color = ~ team_color,
      opacity = 0.6,
      line = list(color = "black",
                  width = 1)
    ),
    width = 625,
    height = 400
  ) %>%
  ### Top right (+Offense +Defense)
  add_annotations(
    x = 14,
    y = 14.5,
    xref = "x",
    yref = "y",
    text = "+ Offense",
    bgcolor = "#67a9cf",
    showarrow = F
  ) %>%
  add_annotations(
    x = 14,
    y = 12.5,
    xref = "x",
    yref = "y",
    text = "+ Defense",
    bgcolor = "#67a9cf",
    showarrow = F
  ) %>%
  ### Bottom left (-Offense -Defense)
  add_annotations(
    x = -13.5,
    y = -14.5,
    xref = "x",
    yref = "y",
    text = "- Offense",
    bgcolor = "#fd5e53",
    showarrow = F
  ) %>%
  add_annotations(
    x = -13.5,
    y = -12.5,
    xref = "x",
    yref = "y",
    text = "- Defense",
    bgcolor = "#fd5e53",
    showarrow = F
  ) %>%
  ### Bottom right (+Offense -Defense)
  add_annotations(
    x = 14,
    y = -12.5,
    xref = "x",
    yref = "y",
    text = "+ Offense",
    bgcolor = "#67a9cf",
    showarrow = F
  ) %>%
  add_annotations(
    x = 14,
    y = -14.5,
    xref = "x",
    yref = "y",
    text = "- Defense",
    bgcolor = "#fd5e53",
    showarrow = F
  ) %>%
  ### Top left (-Offense +Defense)
  add_annotations(
    x = -13.5,
    y = 14.5,
    xref = "x",
    yref = "y",
    text = "- Offense",
    bgcolor = "#fd5e53",
    showarrow = F
  ) %>%
  add_annotations(
    x = -13.5,
    y = 12.5,
    xref = "x",
    yref = "y",
    text = "+ Defense",
    bgcolor = "#67a9cf",
    showarrow = F
  ) %>%
  layout(
    autosize = FALSE,
    xaxis = list(
      range = c(-15.5, 15.5),
      fixedrange = TRUE,
      zeroline = TRUE,
      ticks = "outside",
      tickcolor = "#fff",
      tickformat = "+",
      tickfont = list(size = 14),
      titlefont = list(family = "Open Sans",
                       size = 20),
      title = "Offensive SRS"
    ),
    yaxis = list(
      range = c(-15.5, 15.5),
      fixedrange = TRUE,
      zeroline = TRUE,
      ticks = "outside",
      tickcolor = "#fff",
      tickformat = "+",
      tickfont = list(size = 14),
      titlefont = list(family = "Open Sans",
                       size = 20),
      title = "Defensive SRS"
    ),
    hoverlabel = list(font = list(family = "Open Sans",
                                  size = 16))
  ) %>%
  highlight(on = "plotly_selected") %>%
  config(displayModeBar = FALSE)
```


```{r table}
### Horizontal bar chart to display points scored and points against
bar_chart <-
  function(label,
           width = "100%",
           height = "13px",
           fill = "#00bfc4",
           background = NULL) {
    bar <-
      div(style = list(
        background = fill,
        width = width,
        height = height
      ))
    chart <-
      div(style = list(
        flexGrow = 1,
        marginLeft = "8px",
        background = background
      ),
      bar)
    div(style = list(display = "flex", alignItems = "center"), label, chart)
  }

### Create blue-red color palette for Team Rating SRS columns
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x)
    rgb(get_color(x), maxColorValue = 255)
}

off_rating_color <-
  make_color_pal(c("#fd5e53", "#f8fcf8", "#67a9cf"), bias = 1.3)
def_rating_color <-
  make_color_pal(c("#fd5e53", "#f8fcf8", "#67a9cf"), bias = 0.8)
playoff_color <- 
  make_color_pal(c("#f9fcfb","#b0eacd","#21bf73"))

team_rating_column <- function(maxWidth = 55, ...) {
  colDef(
    maxWidth = maxWidth,
    align = "right",
    class = "cell number",
    headerStyle = list(fontWeight = "500"),
    ...
  )
}

conf_filter <- filter_checkbox(
  id = "conf",
  label = "Conference",
  inline = TRUE,
  sharedData = NFL_table_clean_shared,
  group = ~ Conference
)

div_filter <- filter_select(
  id = "divi",
  label = "Division",
  sharedData = NFL_table_clean_shared,
  group = ~ Division
)

team_filter <- filter_select(
  id = "team",
  label = "Team",
  sharedData = NFL_table_clean_shared,
  group = ~ Team
)

playoff_filter <- filter_slider(
  id = "srs",
  label = "Playoff Odds",
  sharedData = NFL_table_clean_shared,
  column = ~ Playoffs,
  ticks = FALSE,
  post = "%",
  min = 0,
  max = 100,
  step = 10
)

srs_filter <- filter_slider(
  id = "srs",
  label = "Team Rating (SRS): Total",
  sharedData = NFL_table_clean_shared,
  column = ~ SRS,
  ticks = FALSE,
  step = 1
)

div(
  class = "text",
      div(style = "text-align: right",
    "Note: Bubble size represents team's playoff odds according to FiveThirtyEight; click and drag to highlight teams"),
  bscols(
    widths = c(3, NA),
    list(
      srs_filter,
      playoff_filter,
      conf_filter,
      div_filter,
      team_filter
    ),
    interactive_plot
  ),
  tags$br()
)


table <-
    reactable(
      NFL_table_clean_shared,
      pagination = FALSE,
      showSortIcon = FALSE,
      highlight = TRUE,
      compact = TRUE,
      defaultSorted = "Playoffs",
      defaultSortOrder = "desc",
      defaultColDef = colDef(headerClass = "header colheader"),
      columnGroups = list(
        colGroup(
          name = "Team Rating (SRS)",
          columns = c("SRS", "OSRS", "DSRS"),
          headerClass = "groupheader"
        )
        ),
      # Add border between Divisions when sorting by Division
      rowClass = JS("
        function(rowInfo, state) {
          const firstSorted = state.sorted[0]
          if (firstSorted && firstSorted.id === 'Division') {
            const nextRow = state.pageRows[rowInfo.viewIndex + 1]
            if (nextRow && rowInfo.row.Division !== nextRow.Division) {
              return 'last-row-border'
            }
          }
        }"
      ),
      columns = list(
        Division = colDef(
          class = "division-name cell",
          maxWidth = 90),
      Conference = colDef(show = FALSE),
      Team = colDef(
        minWidth = 180,
        class = "cell",
        cell = function(value, index) {
          ### Team logos from images folder
          img_src <- knitr::image_uri(sprintf("images/%s.png", value))
          image <- img(class = "logo",
                     src = img_src,
                     alt = value)
          div(class = "team", image,
            ### Team name
            div(class = "team-name", value),
            ### Team record
            div(class = "record",  sprintf("(%s)", NFL_table_clean[index, "Record"])))
      }
    ), 
        ### Hide record column and team_color column
        Record = colDef(show = FALSE),
        team_color = colDef(show = FALSE),
        SRS = team_rating_column(
          name = "Total",
          cell = function(value) {
            ### Normalize team rating in order to assign color from color palette
            normalized <-
              (value - min(NFL_table_clean$SRS)) / (max(NFL_table_clean$SRS) - min(NFL_table_clean$SRS))
            color <- off_rating_color(normalized)
            value <- format(value, nsmall = 1, digits = 1)
            ### Round corners of cell
            div(class = "roundcorners",
                style = list(background = color),
                value)
          }
        ),
        OSRS = team_rating_column(
          name = "Off.",
          cell = function(value) {
            ### Normalize team rating in order to assign color from color palette
            normalized <-
              (value - min(NFL_table_clean$OSRS)) / (max(NFL_table_clean$OSRS) - min(NFL_table_clean$OSRS))
            color <- off_rating_color(normalized)
            value <- format(value, nsmall = 1, digits = 1)
            ### Round corners of cell
            div(class = "roundcorners",
                style = list(background = color),
                value)
          }
        ),
        DSRS = team_rating_column(
          name = "Def.",
          cell = function(value) {
          ### Normalize team rating in order to assign color from color palette
            normalized <-
              (value - min(NFL_table_clean$DSRS)) / (max(NFL_table_clean$DSRS) - min(NFL_table_clean$DSRS))
            color <- off_rating_color(normalized)
            value <- format(value, nsmall = 1, digits = 1)
            ### Round corners of cell
            div(class = "roundcorners",
                style = list(background = color),
                value)
          }
        ),
        PF = colDef(
          name = "Points Scored",
          align = "left",
          ### Add column border to left side of column
          class = "border-left cell number",
          # headerStyle = list(fontWeight = "500"),
          cell = function(value) {
            ### Calculate width of bar color to display
            width <- paste0(value / max(NFL_table_clean$PF) * 100, "%")
            bar_chart(value,
                      width = width,
                      fill = "#ef8a62",
                      background = "#e1e1e1")
          }
        ),
        PA = colDef(
          name = "Points Against",
          align = "left",
          class = "border-right cell number",
          # headerStyle = list(fontWeight = "500"),
          cell = function(value) {
            ### Calculate width of bar color to display
            width <- paste0(value / max(NFL_table_clean$PA) * 100, "%")
            bar_chart(value,
                      width = width,
                      fill = "#ef8a62",
                      background = "#e1e1e1")
          }
        ),
        SoS_rating = colDef(
          name = "SoS",
          align = "center",
          maxWidth = 50,
          class = "cell number border-left ",
          cell = function(value) {
          ### For teams that were assigned a SoS_rating of 4 (highest rating), show a double-black diamond (note: there was no diamond icon available in the Font Awesome Free library, so the solution was to use a square icon and rotate it at a 45 degree angle)
            if (value == 4) {
              ### In order to display two icons in the same column, they need to be placed in a list
              list(tagAppendAttributes(shiny::icon("square", class = "rotate")),
                   tagAppendAttributes(shiny::icon("square", class = "rotate")))
              ### For teams that were assigned a SoS_rating of 3, show a single black diamond
            } else if (value == 3) {
              tagAppendAttributes(shiny::icon("square", class = "rotate"))
              ### For teams that were assigned a SoS_rating of 2, show a blue square
            } else if (value == 2) {
              tagAppendAttributes(shiny::icon("square"))
            } else {
              ### For teams that were assigned a SoS_rating of 1, show a green circle
              tagAppendAttributes(shiny::icon("circle"))
            }
          },
          style = function(value) {
            ### Assign colors to icons
            if (value %in% c(3, 4)) {
              color <- "black"
            } else if (value == 2) {
              color <- "blue"
            } else {
              color <- "green"
            }
            list(color = color)
          }
        ),
        Playoff_labels = colDef(show = FALSE),
        Playoffs = colDef(
          name = "538 Playoff Odds",
          class = "cell number border-left",
          align = "center",
          maxWidth = 75,
          cell = function(value) {
            normalized <-
              (value - min(NFL_table_clean$Playoffs)) / (max(NFL_table_clean$Playoffs) - min(NFL_table_clean$Playoffs))
            value <- ifelse(value == 0.1, " <1%", 
                            ifelse(value == 99.9, ">99%", paste0(value, "%")))
            div(style = list(fontWeight = "bold",
                             background = playoff_color(normalized)),
                value)
          }
        )
      )
    )

### Add title and subtitle to top of page above table
div(class = "team-ratings",
    # div(class = "title",
    #     h2("2020 NFL Team Rating & Stats")),
        # "Ratings and results from every NFL team from the 2020 season"),
  table,
  ### Add legend and source below the table
  tags$span(
    style = "color:#777",
    "Note: Strength of Schedule (SoS) aligns with the ski trail difficulty rating system:", 
    ### In order to display icons with color, needed to create a new css class for the symbols that contained a color option
    tagAppendAttributes(shiny::icon("circle", class = "green-circle-legend")), "= Easy",
    tagAppendAttributes(shiny::icon("square", class = "blue-square-legend")), "= Moderate",  
    tagAppendAttributes(shiny::icon("square", class = "black-diamond-legend1")), "= Difficult", 
    list(tagAppendAttributes(shiny::icon("square", class = "black-diamond-legend1")),
                   tagAppendAttributes(shiny::icon("square", class = "black-diamond-legend2"))), "= Most Difficult",
    div(
    "Table created by: Kyle Cuilla @kc_analytics  •  Data: Pro-Football-Reference.com & FiveThirtyEight.com")
  )
)
```

```{r}
### Load font from Google Fonts
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css}
/* Row and column borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.07);
}

.border-left {
  border-left: 1px solid #777;
}

.border-right {
  border-right: 1px solid #777;
}

.last-row-border .cell {
  box-shadow: inset 0 -1px 0 #777;
}


/* Column hover formatting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #dadada;
}

.header:active,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #333;
  color: #fff;
}


/* Column header formatting */
.colheader {
  font-family: "Open Sans", sans-serif;
  font-size: 15px;
  border-bottom: 2px solid #555;
}

.groupheader {
  font-family: "Open Sans", sans-serif;
  font-size: 15px;
}


/* Number formatting */
.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 13px;
  line-height: 30px;
  white-space: pre;
}

/* Text formatting */
.team-ratings {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 12px;
}


/* Division column formatting */
.division-name {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 30px;
}


/* Team column formatting */
.team {
  display: flex;
  align-items: baseline;
}

.logo {
  margin-right: 10px;
  height: 24px;
}

.team-name {
  font-size: 14px;
  font-weight: 700;
}

.record {
  margin-left: 4px;
  color: #999;
  font-size: 13px;
}


/* Rotate SoS square into a diamond */
.rotate{
  transform: rotate(45deg);
}


/* Round corners under Team Rating columns */
.roundcorners {
  border-radius: 10px;
  color: #000;
  padding-bottom: 2px;
  padding-right: 2px;
  width: 46px;
  height: 28px;
}


/* Formatting for title above table */
.title {
  font-family: "Open Sans", sans-serif;
  font-size: 16px;
  margin: 16px 0;
}


/* SoS legend symbols underneath chart */
.black-diamond-legend1{
  transform: rotate(45deg);
  color: #000;
  margin-left: 7px;
}

.black-diamond-legend2{
  transform: rotate(45deg);
  color: #000;
}

.green-circle-legend{
  color: #008000;
  margin-left: 7px;
}

.blue-square-legend{
  color: #0000FF;
  margin-left: 7px;
}
```


